build_cc7:
    image: gitlab-registry.cern.ch/linuxsupport/cc7-base
    stage: build
    script:
        - yum install -y gcc kernel kernel-devel kernel-headers make libelf-dev elfutils-libelf-devel
        - cd src
        - make KERNELDIR=/lib/modules/$(ls /lib/modules)/build

build_c8:
    image: gitlab-registry.cern.ch/linuxsupport/c8-base
    stage: build
    script:
        - yum install -y gcc kernel kernel-devel kernel-headers make elfutils-libelf-devel
        - cd src
        - make KERNELDIR=/lib/modules/$(ls /lib/modules)/build

build_cs8:
    image: gitlab-registry.cern.ch/linuxsupport/cs8-base
    stage: build
    script:
        - yum install -y gcc kernel kernel-devel kernel-headers make elfutils-libelf-devel
        - cd src
        - make KERNELDIR=/lib/modules/$(ls /lib/modules)/build

build_cs9:
    image: gitlab-registry.cern.ch/linuxsupport/cs9-base
    stage: build
    script:
        - yum install -y gcc kernel kernel-devel kernel-headers make elfutils-libelf-devel
        - cd src
        - make KERNELDIR=/lib/modules/$(ls /lib/modules)/build

build_u22:
    image: docker.io/library/ubuntu:22.04
    stage: build
    script:
        - apt update
        - apt -y install build-essential linux-headers-generic
        - ls /lib/modules
        - cd src 
        - make KERNELDIR=/lib/modules/$(ls /lib/modules)/build

build_u23:
    image: docker.io/library/ubuntu:23.04
    stage: build
    script:
        - apt update
        - apt -y install build-essential linux-headers-generic
        - ls /lib/modules
        - cd src
        - make KERNELDIR=/lib/modules/$(ls /lib/modules)/build

build_alma9:
    image: gitlab-registry.cern.ch/linuxsupport/alma9-base
    stage: build
    script:
        - yum install -y gcc kernel kernel-devel kernel-headers make elfutils-libelf-devel
        - cd src
        - make KERNELDIR=/lib/modules/$(ls /lib/modules)/build


build_u22_hwe:
    image: docker.io/library/ubuntu:22.04
    stage: build
    script:
        - apt update
        - apt -y install build-essential linux-headers-generic-hwe-22.04
        - ls /lib/modules
        - cd src 
        - make KERNELDIR=/lib/modules/$(ls /lib/modules)/build
